# Generated by Django 3.0.1 on 2020-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thematicArea', models.CharField(blank=True, max_length=300)),
                ('eligibility', models.CharField(blank=True, max_length=300)),
                ('option', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('additional', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
