# Generated by Django 3.0.1 on 2020-06-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finoption',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='finoption',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='finoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='finoption',
            name='thematicArea',
        ),
        migrations.RemoveField(
            model_name='finoption',
            name='title',
        ),
        migrations.AddField(
            model_name='finoption',
            name='ApplicationProcessDates',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ApplicationProcessDuration',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ApplicationProcessPotentiality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ApplicationProcessSteps',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ContactComment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ContactEmail',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ContactGuidelinesDownload',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ContactRecommendations',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ContactWebsite',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='EligibilityApplicants',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='finoption',
            name='EligibilityCriteria',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='finoption',
            name='EligibilityGov',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='EligibilityNonGov',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='finoption',
            name='EligibilityProjectPreparationLevel',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='EligibilityProjectType',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='finoption',
            name='EligibilityProjectValueRange',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='FilterEligble',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='FilterFinancingOption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='FilterThematicArea',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='InstCategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='InstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='InstPartnerStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='InstType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='OptionAidModalities',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='OptionFinancingOption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='OptionFundTitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='OptionTenor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='OptionTenorYears',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='Status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ThemeArea',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ThemeKeySubsector',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ThemePlannedAllocations',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='finoption',
            name='ThemeTarget',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
