# Generated by Django 3.0.1 on 2020-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_thematicarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eligibility', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinancingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FinancingOption', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
